#!/bin/bash

usage() {
  cat <<HERETO
Usage: ./manage [command]

Commands:
    init-frontend   Downloads dependencies for React through yarn

    init-backend    Initializes python venv, downloads dependencies, initializes Database

    start-frontend  Alias for "yarn start"

    start-backend   Alias for "python manage.py runserver"

    lint            Runs ESLint and flake8
HERETO
}

init-frontend() {
  pushd frontend
  yarn
  popd
}

init-backend() {
  pushd backend
  mkdir dev_logs
  python3 -m venv env
  env/bin/pip install --upgrade pip
  env/bin/pip install -r requirements.txt
  env/bin/python manage.py migrate
  env/bin/python manage.py runscript seed_db
  popd
}

start-frontend() {
  cd frontend
  yarn start
}

start-backend() {
  cd backend
  env/bin/python manage.py runserver
}

clean-backend() {
  pushd backend
  python3 -Bc "import pathlib; [p.unlink() for p in pathlib.Path('.').rglob('*.py[co]')]"
  python3 -Bc "import pathlib; [p.rmdir() for p in pathlib.Path('.').rglob('__pycache__')]"
  popd
}

build() {
  pushd frontend
  yarn build
  cd ../backend
  env/bin/python manage.py collectstatic --noinput
  popd
}

deploy() {
  # This will only work from my machine since I have the proper ssh keys
  ssh root@continuum-loot.tfrom.me 'rm -rf /etc/continuum-loot/build'
  pushd frontend
  scp -r build root@continuum-loot.tfrom.me:/etc/continuum-loot
  cd ..

  clean-backend

  cd backend
  ssh root@continuum-loot.tfrom.me 'rm -rf /etc/continuum-loot/backend/continuum_loot'
  ssh root@continuum-loot.tfrom.me 'rm -rf /etc/continuum-loot/backend/loot'
  ssh root@continuum-loot.tfrom.me 'rm -rf /etc/continuum-loot/backend/scripts'
  scp -r continuum_loot root@continuum-loot.tfrom.me:/etc/continuum-loot/backend
  scp -r loot root@continuum-loot.tfrom.me:/etc/continuum-loot/backend
  scp -r scripts root@continuum-loot.tfrom.me:/etc/continuum-loot/backend
  scp manage.py requirements.txt root@continuum-loot.tfrom.me:/etc/continuum-loot/backend
  ssh root@continuum-loot.tfrom.me 'cd /etc/continuum-loot/backend && env/bin/pip install -r requirements.txt && env/bin/python manage.py migrate'
  ssh root@continuum-loot.tfrom.me 'service continuum-loot-api restart'

  popd
}

lint() {
  pushd frontend > /dev/null
  node_modules/.bin/eslint src/
  cd ../backend
  env/bin/flake8 --exclude __pycache__,migrations manage.py continuum_loot scripts loot
  popd > /dev/null
}

cmd="$1"
case "$cmd" in 
  init-frontend|init-backend|start-frontend|start-backend|build|deploy|lint )
    $@
    ;;
  * )
    usage
    ;;
esac
