# Generated by Django 3.1.2 on 2020-10-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Inactive'), (10, 'Pug'), (20, 'Trial'), (30, 'Member'), (40, 'Veteran'), (50, 'Core Raider'), (60, 'Class Lead'), (70, 'Officer'), (80, 'GM')], default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('D', 'DPS'), ('T', 'Tank'), ('H', 'Healer')], default='D', max_length=1),
        ),
    ]
