# Generated by Django 3.1.2 on 2020-10-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loot', '0002_auto_20201003_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'verbose_name_plural': 'Bosses'},
        ),
        migrations.AlterModelOptions(
            name='classprio',
            options={'verbose_name': 'Class Prio', 'verbose_name_plural': 'Class Prios'},
        ),
        migrations.AlterModelOptions(
            name='individualprio',
            options={'verbose_name': 'Individual Prio', 'verbose_name_plural': 'Individual Prios'},
        ),
        migrations.AlterModelOptions(
            name='loothistory',
            options={'verbose_name': 'Loot History', 'verbose_name_plural': 'Loot History'},
        ),
        migrations.AlterModelOptions(
            name='raidday',
            options={'verbose_name': 'Raid Day', 'verbose_name_plural': 'Raid Days'},
        ),
        migrations.AlterField(
            model_name='classprio',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='individualprio',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tier',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='attendance',
            field=models.ManyToManyField(blank=True, to='loot.RaidDay'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
