# Generated by Django 3.1.2 on 2020-10-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0004_auto_20201004_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
