# Generated by Django 3.1.2 on 2020-10-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0006_auto_20201005_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='order',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
