# Generated by Django 3.1.2 on 2020-10-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0007_boss_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'ordering': ['order'], 'verbose_name_plural': 'Bosses'},
        ),
    ]
