# Generated by Django 3.1.2 on 2020-10-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0008_auto_20201006_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alts',
            field=models.ManyToManyField(related_name='_player_alts_+', to='loot.Player'),
        ),
    ]
