# Generated by Django 3.1.2 on 2020-10-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0009_player_alts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='alts',
            field=models.ManyToManyField(blank=True, related_name='_player_alts_+', to='loot.Player'),
        ),
    ]
