# Generated by Django 3.1.2 on 2020-11-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0011_player_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raidday',
            options={'ordering': ['-date'], 'verbose_name': 'Raid Day', 'verbose_name_plural': 'Raid Days'},
        ),
    ]
