# Generated by Django 3.1.2 on 2020-11-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0012_auto_20201102_0308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raidday',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Raid Day', 'verbose_name_plural': 'Raid Days'},
        ),
    ]
